### ISSUE TITLE
为何如此叼的框架不兼容4.0版本

### ISSUE THREAD

**Issue by ynting** [neccy/AhSweetAlertDialog#1]
为何如此叼的框架不兼容4.0版本

**Comment by neccy** [comment]
不好意思，我没在4.0上做测试。你去网上搜一下，应该能找到原创的。我对原创的修改，只是适配了android 7.0
----- 原始邮件 -----
发件人：dingputongxi <notifications@github.com>
收件人：neccy/AhSweetAlertDialog <AhSweetAlertDialog@noreply.github.com>
抄送人：Subscribed <subscribed@noreply.github.com>
主题：[neccy/AhSweetAlertDialog]_为何如此叼的框架不兼容4.0版本_(#1)
日期：2018年04月18日 17点49分

为何如此叼的框架不兼容4.0版本

&mdash;
